# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!pip install pandas

!pip install tabulate

import requests
from bs4 import BeautifulSoup
import pandas as pd
from tabulate import tabulate
import matplotlib.pyplot as plt

url = "https://www.fossjobs.net/jobs/"

# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the HTML content of the page
    soup = BeautifulSoup(response.content, 'html.parser')

    # Extract information based on the HTML structure of the page
    job_data = []

    # Assuming each job is contained within an article tag with class 'post'
    for job_article in soup.find_all('article', class_='post'):
        # Extracting job information based on the observed structure
        job_title = job_article.find('h2').find('a').text.strip()
        job_company = job_article.find('a', class_='neutral-link').text.strip()

        # Extracting date, location, and employment type information
        job_info = job_article.find('div', class_='content').text.strip().split('\n')
        job_date = job_info[1].strip()
        job_location = job_info[2].strip()

        # Extracting employment type
        job_employment_type = job_article.find('span', class_='tag').text.strip() if job_article.find('span', class_='tag') else ''

        # Append job data to the list
        job_data.append({
            'Job Title': job_title,
            'Company': job_company,
            'Date': job_date,
            'Location': job_location,
            'Employment Type': job_employment_type
        })

    # Create a Pandas DataFrame from the list of job data
    job_df = pd.DataFrame(job_data)

    # Display the DataFrame using tabulate
    print(tabulate(job_df, headers='keys', tablefmt='pretty'))

    # Save the DataFrame to a CSV file
    job_df.to_csv('job_data.csv', index=False)

    # Count the number of job listings per company
    company_counts = job_df['Company'].value_counts()

    # Create a bar chart
    plt.figure(figsize=(10, 6))
    company_counts.plot(kind='bar', color='skyblue')
    plt.title('Number of Job Listings per Company')
    plt.xlabel('Company')
    plt.ylabel('Number of Job Listings')
    plt.xticks(rotation=45, ha='right')
    plt.show()

# Download the CSV file
    from google.colab import files
    files.download('/content/job_data.csv')
else:
    print(f"Failed to retrieve the page. Status code: {response.status_code}")